### ISSUE TITLE
NoSuchBucket The specified bucket does not exist bff 7a62c49f-347e-4fc4-9331-6e8eEXAMPLE

### ISSUE THREAD

**Issue by moujibbouchech** [serverless-community-labs/serverless-plugin-simulate#70]
# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Serverless Docker Plugin Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by johncmckim** [comment]
Hi @moujibbouchech can you please fill out the issue template above? It's quite hard to know what has gone wrong just from that title?

**Comment by nielslanting** [comment]
This seems to be what you get when you run the example.
The docker-compose.yml exposes the moto s3 service on port 5000.
The npm start:apigateway starts at port 5000 too. Why is this?

Changing the start port for apigateway will resolve this issue.

**Comment by johncmckim** [comment]
I've updated the example as you suggested @nielslanting. Thanks so much for spotting this.

@moujibbouchech feel free to re-open if this does not solve the problem.

**Comment by CarlosV89** [comment]
Hey guys, im having the same issue he's having, hopefully I can give you more information.


-  What went wrong?
```
Could not connect to the endpoint URL: "http://0.0.0.0:5000/xxxx-xxxxx": EndpointConnectionError
```
- What did you expect should have happened?
s3 was correctly mocked in localhost as per `docker-compose.yml`
- What was the config you used?
`docker-compose.yml`
```
version: '2'

services:
  s3:
    build: moto/s3
    command: [s3, "-H", "0.0.0.0"]
    ports:
      - "5000:5000"
```

`moto/s3/Dockerfile`
```
FROM python:3.6
RUN pip3 install moto[server]

# Create boto endpoints.json with "moto" region
COPY endpoints.json /opt/moto/
VOLUME ["/opt/moto"]

# Default port that moto listens on.
EXPOSE 5000

ENTRYPOINT ["moto_server"]
CMD ["s3"]
```
- What stacktrace or error message from your provider did you see?
```
Could not connect to the endpoint URL: "http://0.0.0.0:5000/ClassifierModelsBucket-dev": Endpo
intConnectionError
Traceback (most recent call last):
  File "/var/task/handlers.py", line 37, in train
    return train_handler(classifier_id)
  File "/var/task/modules/train.py", line 83, in handler
    upload(file_location, bucket_name, file_name)
  File "/var/task/modules/utils/aws.py", line 13, in upload
    s3.create_bucket(Bucket=bucket_name)
  File "/var/lang/lib/python3.6/site-packages/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/lang/lib/python3.6/site-packages/botocore/client.py", line 610, in _make_api_call
    operation_model, request_dict)
  File "/var/lang/lib/python3.6/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/var/lang/lib/python3.6/site-packages/botocore/endpoint.py", line 136, in _send_reques
t
    success_response, exception):
  File "/var/lang/lib/python3.6/site-packages/botocore/endpoint.py", line 210, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/var/lang/lib/python3.6/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/var/lang/lib/python3.6/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/var/lang/lib/python3.6/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/var/lang/lib/python3.6/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/var/lang/lib/python3.6/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/var/lang/lib/python3.6/site-packages/botocore/retryhandler.py", line 277, in _should_
retry
    return self._checker(attempt_number, response, caught_exception)
  File "/var/lang/lib/python3.6/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/var/lang/lib/python3.6/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/var/lang/lib/python3.6/site-packages/botocore/retryhandler.py", line 359, in _check_c
aught_exception
    raise caught_exception
  File "/var/lang/lib/python3.6/site-packages/botocore/endpoint.py", line 179, in _get_respons
e
    http_response = self._send(request)
  File "/var/lang/lib/python3.6/site-packages/botocore/endpoint.py", line 223, in _send
    return self.http_session.send(request)
  File "/var/lang/lib/python3.6/site-packages/botocore/httpsession.py", line 278, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "http://0.
0.0.0:5000/ClassifierModelsBucket-dev"
```

I have moto exposed at port 5000 as you can see.
I simulate lambda at port 4200 and apigateway at 7100, when I create the s3 client, I tell boto3 to use `http://0.0.0.0:5000`.

```
s3 = boto3.client(service_name='s3',
                          endpoint_url='http://0.0.0.0:5000')
        s3.create_bucket(Bucket=bucket_name)
```

What am I missing?
